#!/usr/bin/env python3
import sys
import os
import argparse

import ghslib

parser = argparse.ArgumentParser()
parser.add_argument("query")
parser.add_argument("--no-cache", action="store_true")
parser.add_argument("--server", default=ghslib.github_graphql_server)
args = parser.parse_args()

response = ghslib.get_graphql(args.query, no_cache = args.no_cache, server = args.server)
print(response)
